// Canonical 66-book list (KJV order) with testament.
// Useful for validating imports and deriving OT/NT.

const BOOKS = [
  // Old Testament
  { name: 'Genesis', testament: 'Old Testament' },
  { name: 'Exodus', testament: 'Old Testament' },
  { name: 'Leviticus', testament: 'Old Testament' },
  { name: 'Numbers', testament: 'Old Testament' },
  { name: 'Deuteronomy', testament: 'Old Testament' },
  { name: 'Joshua', testament: 'Old Testament' },
  { name: 'Judges', testament: 'Old Testament' },
  { name: 'Ruth', testament: 'Old Testament' },
  { name: '1 Samuel', testament: 'Old Testament' },
  { name: '2 Samuel', testament: 'Old Testament' },
  { name: '1 Kings', testament: 'Old Testament' },
  { name: '2 Kings', testament: 'Old Testament' },
  { name: '1 Chronicles', testament: 'Old Testament' },
  { name: '2 Chronicles', testament: 'Old Testament' },
  { name: 'Ezra', testament: 'Old Testament' },
  { name: 'Nehemiah', testament: 'Old Testament' },
  { name: 'Esther', testament: 'Old Testament' },
  { name: 'Job', testament: 'Old Testament' },
  { name: 'Psalms', testament: 'Old Testament' },
  { name: 'Proverbs', testament: 'Old Testament' },
  { name: 'Ecclesiastes', testament: 'Old Testament' },
  { name: 'Song of Solomon', testament: 'Old Testament' },
  { name: 'Isaiah', testament: 'Old Testament' },
  { name: 'Jeremiah', testament: 'Old Testament' },
  { name: 'Lamentations', testament: 'Old Testament' },
  { name: 'Ezekiel', testament: 'Old Testament' },
  { name: 'Daniel', testament: 'Old Testament' },
  { name: 'Hosea', testament: 'Old Testament' },
  { name: 'Joel', testament: 'Old Testament' },
  { name: 'Amos', testament: 'Old Testament' },
  { name: 'Obadiah', testament: 'Old Testament' },
  { name: 'Jonah', testament: 'Old Testament' },
  { name: 'Micah', testament: 'Old Testament' },
  { name: 'Nahum', testament: 'Old Testament' },
  { name: 'Habakkuk', testament: 'Old Testament' },
  { name: 'Zephaniah', testament: 'Old Testament' },
  { name: 'Haggai', testament: 'Old Testament' },
  { name: 'Zechariah', testament: 'Old Testament' },
  { name: 'Malachi', testament: 'Old Testament' },

  // New Testament
  { name: 'Matthew', testament: 'New Testament' },
  { name: 'Mark', testament: 'New Testament' },
  { name: 'Luke', testament: 'New Testament' },
  { name: 'John', testament: 'New Testament' },
  { name: 'Acts', testament: 'New Testament' },
  { name: 'Romans', testament: 'New Testament' },
  { name: '1 Corinthians', testament: 'New Testament' },
  { name: '2 Corinthians', testament: 'New Testament' },
  { name: 'Galatians', testament: 'New Testament' },
  { name: 'Ephesians', testament: 'New Testament' },
  { name: 'Philippians', testament: 'New Testament' },
  { name: 'Colossians', testament: 'New Testament' },
  { name: '1 Thessalonians', testament: 'New Testament' },
  { name: '2 Thessalonians', testament: 'New Testament' },
  { name: '1 Timothy', testament: 'New Testament' },
  { name: '2 Timothy', testament: 'New Testament' },
  { name: 'Titus', testament: 'New Testament' },
  { name: 'Philemon', testament: 'New Testament' },
  { name: 'Hebrews', testament: 'New Testament' },
  { name: 'James', testament: 'New Testament' },
  { name: '1 Peter', testament: 'New Testament' },
  { name: '2 Peter', testament: 'New Testament' },
  { name: '1 John', testament: 'New Testament' },
  { name: '2 John', testament: 'New Testament' },
  { name: '3 John', testament: 'New Testament' },
  { name: 'Jude', testament: 'New Testament' },
  { name: 'Revelation', testament: 'New Testament' },
];

const BOOK_TO_TESTAMENT = Object.fromEntries(BOOKS.map(b => [b.name, b.testament]));

module.exports = { BOOKS, BOOK_TO_TESTAMENT };

